CREATE TABLE "PUBLIC"."DWH_ALF_DIM_USERS"
(
   ID integer IDENTITY PRIMARY KEY NOT NULL,
   USER_NAME varchar(1024) NOT NULL,
   FIRST_NAME varchar(1024) NOT NULL,
   LAST_NAME varchar(1024),
   EMAIL varchar(1024) NOT NULL,
   JOB_TITLE varchar(1024),
   ORGANIZATION varchar(1024),
   ENABLED CHARACTER NOT NULL,
   EMAIL_NOTIFICATIONS_ENABLED CHARACTER NOT NULL,
   INSTANCE_ID smallint NOT NULL,
   SRC_ID varchar(1024) NOT NULL
)
;
ALTER TABLE "PUBLIC"."DWH_ALF_DIM_USERS"
ADD CONSTRAINT FK_DWH_ALF_DIM_USERS_DWH_ALF_DIM_INSTANCES
FOREIGN KEY (INSTANCE_ID)
REFERENCES "PUBLIC"."DWH_ALF_DIM_INSTANCES"(ID) ON DELETE CASCADE ON UPDATE CASCADE
;
CREATE UNIQUE INDEX IDX_PK_DWH_ALF_DIM_USERS ON "PUBLIC"."DWH_ALF_DIM_USERS"(ID)
;
CREATE INDEX IDX_DWH_ALF_DIM_USERS_SRC_ID ON "PUBLIC"."DWH_ALF_DIM_USERS"(SRC_ID)
;

CREATE UNIQUE INDEX IDX_UNQ__DWH_ALF_DIM_USERS ON "PUBLIC"."DWH_ALF_DIM_USERS"
(
  INSTANCE_ID,
  SRC_ID
)
;






CREATE TABLE "dm_dim_alfresco" (
    "id" smallint NOT NULL PRIMARY KEY,
    "description" VARCHAR(25) NOT NULL,
    "login" VARCHAR(128) NOT NULL,
    "password" VARCHAR(128) NOT NULL,
    "protocol" VARCHAR(8) NOT NULL,
    "host" VARCHAR(128) NOT NULL,
    "port" VARCHAR(8) NOT NULL,
    "rest_api_prefix" VARCHAR(1024) NOT NULL,
    "audit_limit" integer NOT NULL,
    "node_limit" integer NOT NULL,
    "workflow_limit" integer NOT NULL,
    "is_active" CHAR(1) DEFAULT 'Y' NOT NULL
);

INSERT INTO "dm_dim_alfresco" (
"id","description","login","password","protocol","host","port","audit_limit","node_limit","workflow_limit","is_active"
) VALUES (
1,'Alfresco','admin',
'admin','http',
'localhost','8080',
50000,50000,
50000,'Y');

CREATE TABLE "dm_data_quality" (
    "alfresco_id" smallint NOT NULL,
    "batch_id" VARCHAR(128) NOT NULL,
    "entities" VARCHAR(128) NOT NULL,
    "layer" VARCHAR(128) NOT NULL,
    "value" integer NOT NULL,
    "creation" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE "dm_data_quality" ADD CONSTRAINT "fk_dm_data_quality_dm_dim_alfresco" FOREIGN KEY ( "alfresco_id" ) REFERENCES "dm_dim_alfresco" ( "id" );

CREATE TABLE "dm_data_quality_logs" (
    "alfresco_id" smallint NOT NULL,
    "batch_id" VARCHAR(128) NOT NULL,
    "description" VARCHAR(256) NOT NULL,
    "batch_start" timestamp without time zone NOT NULL,
    "batch_end" timestamp without time zone NOT NULL,
    "success" CHAR(1) NOT NULL
);

ALTER TABLE "dm_data_quality_logs" ADD CONSTRAINT "fk_dm_data_quality_logs_dm_dim_alfresco" FOREIGN KEY ( "alfresco_id" ) REFERENCES "dm_dim_alfresco" ( "id" );









CREATE TABLE "dm_custom_metadata" (
    "id" smallint GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL,
    "class" VARCHAR(255) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "type" VARCHAR(255) NOT NULL,
    "is_document_subtype" CHAR(1) DEFAULT 'N' NOT NULL,
    "is_folder_subtype" CHAR(1) DEFAULT 'N' NOT NULL,
    "is_aspect" CHAR(1) DEFAULT 'N' NOT NULL,
    "is_active" CHAR(1) DEFAULT 'Y' NOT NULL,
    "alfresco_id" smallint NOT NULL
);



CREATE TABLE "dm_dim_actions" (
    "id" smallint GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL,
    "desc" VARCHAR(128) NOT NULL,
    "alfresco_id" smallint NOT NULL,
    "src_action" VARCHAR(128) NOT NULL
);

CREATE TABLE "dm_dim_dates" (
    "id" DATE NOT NULL,
    "desc" VARCHAR(64) NOT NULL,
    "day_desc" VARCHAR(64) NOT NULL,
    "month_id" DATE NOT NULL
);

CREATE TABLE "dm_dim_documents" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL,
    "store-protocol" VARCHAR(128) NOT NULL,
    "store-identifier" VARCHAR(128) NOT NULL,
    "node-uuid" VARCHAR(128) NOT NULL,
    "name" VARCHAR(1024) NOT NULL,
    "path" VARCHAR(4096) NOT NULL,
    "node_type_id" smallint NOT NULL,
    "mime_type_id" smallint NOT NULL,
    "user_creator_id" integer NOT NULL,
    "creation_date_id" DATE,
    "creation_minute_id" smallint NOT NULL,
    "user_last_modifier_id" integer NOT NULL,
    "last_modification_date_id" DATE NOT NULL,
    "last_modification_minute_id" smallint NOT NULL,
    "size" integer NOT NULL,
    "parent_id" integer NOT NULL,
    "alfresco_id" smallint NOT NULL,
    "src_id" integer NOT NULL
);

CREATE TABLE "dm_dim_folders" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL,
    "store-protocol" VARCHAR(128) NOT NULL,
    "store-identifier" VARCHAR(128) NOT NULL,
    "node-uuid" VARCHAR(128) NOT NULL,
    "name" VARCHAR(1024) NOT NULL,
    "path" VARCHAR(4096) NOT NULL,
    "node_type_id" smallint NOT NULL,
    "user_creator_id" integer NOT NULL,
    "creation_date_id" DATE,
    "creation_minute_id" smallint NOT NULL,
    "user_last_modifier_id" integer NOT NULL,
    "last_modification_date_id" DATE NOT NULL,
    "last_modification_minute_id" smallint NOT NULL,
    "parent_id" integer,
    "alfresco_id" smallint NOT NULL,
    "src_id" integer NOT NULL
);

CREATE TABLE "dm_dim_hours" (
    "id" smallint NOT NULL,
    "desc" VARCHAR(16) NOT NULL
);

CREATE TABLE "dm_dim_mime_types" (
    "id" smallint GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL,
    "desc" VARCHAR(512) NOT NULL,
    "alfresco_id" smallint NOT NULL,
    "src_id" VARCHAR(512) NOT NULL
);

CREATE TABLE "dm_dim_minutes" (
    "id" smallint NOT NULL,
    "desc" VARCHAR(16) NOT NULL,
    "hour_id" smallint NOT NULL
);

CREATE TABLE "dm_dim_months" (
    "id" DATE NOT NULL,
    "desc" VARCHAR(64) NOT NULL,
    "month_desc" VARCHAR(64) NOT NULL,
    "year_id" smallint NOT NULL
);

CREATE TABLE "dm_dim_node_types" (
    "id" smallint GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL,
    "desc" VARCHAR(512) NOT NULL,
    "base_type" VARCHAR(512) NOT NULL,
    "alfresco_id" smallint NOT NULL,
    "src_id" VARCHAR(512) NOT NULL
);

CREATE TABLE "dm_dim_paths" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL,
    "path" VARCHAR(4096) NOT NULL,
    "folder_id" integer,
    "document_id" integer,
    "alfresco_id" smallint NOT NULL,
    "src_path" VARCHAR(4096) NOT NULL
);


CREATE TABLE "dm_dim_users" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL,
    "desc" VARCHAR(512) NOT NULL,
    "alfresco_id" smallint NOT NULL,
    "src_user" VARCHAR(512) NOT NULL
);

CREATE TABLE "dm_dim_workflow_definitions" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL,
    "name" VARCHAR(1024) NOT NULL,
    "title" VARCHAR(1024) NOT NULL,
    "desc" VARCHAR(1024) NOT NULL,
    "version" VARCHAR(64) NOT NULL,
    "url" VARCHAR(1024) NOT NULL,
    "alfresco_id" smallint NOT NULL,
    "src_id" VARCHAR(1024) NOT NULL
);

CREATE TABLE "dm_dim_workflow_instances" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL,
    "definition_id" integer NOT NULL,
    "name" VARCHAR(1024) NOT NULL,
    "title" VARCHAR(1024) NOT NULL,
    "desc" VARCHAR(1024) NOT NULL,
    "is_active" VARCHAR(16) NOT NULL,
    "initiator_id" integer NOT NULL,
    "start_date_id" DATE NOT NULL,
    "start_minute_id" smallint NOT NULL,
    "due_date_id" DATE NOT NULL,
    "due_minute_id" smallint NOT NULL,
    "end_date_id" DATE NOT NULL,
    "end_minute_id" smallint NOT NULL,
    "diagram_url" VARCHAR(1024) NOT NULL,
    "duration" integer,
    "max_duration" integer,
    "alfresco_id" smallint NOT NULL,
    "src_id" VARCHAR(1024) NOT NULL
);

CREATE TABLE "dm_dim_workflow_items" (
    "workflow_instance_id" integer NOT NULL,
    "document_id" integer NOT NULL,
    "ordinal" smallint NOT NULL,
    "alfresco_id" smallint NOT NULL
);

CREATE TABLE "dm_dim_workflow_tasks" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL,
    "instance_id" integer NOT NULL,
    "name" VARCHAR(1024) NOT NULL,
    "title" VARCHAR(1024) NOT NULL,
    "desc" VARCHAR(1024) NOT NULL,
    "state" VARCHAR(64) NOT NULL,
    "status" VARCHAR(64) NOT NULL,
    "owner_id" integer NOT NULL,
    "is_pooled" VARCHAR(16) NOT NULL,
    "is_editable" VARCHAR(16) NOT NULL,
    "is_reassignable" VARCHAR(16) NOT NULL,
    "is_claimable" VARCHAR(16) NOT NULL,
    "outcome" VARCHAR(128) NOT NULL,
    "start_date_id" DATE NOT NULL,
    "start_minute_id" smallint NOT NULL,
    "due_date_id" DATE NOT NULL,
    "due_minute_id" smallint NOT NULL,
    "completion_date_id" DATE NOT NULL,
    "completion_minute_id" smallint NOT NULL,
    "duration" integer NOT NULL,
    "max_duration" integer NOT NULL,
    "ordinal" smallint NOT NULL,
    "alfresco_id" smallint NOT NULL,
    "src_id" VARCHAR(1024) NOT NULL
);

CREATE TABLE "dm_dim_years" (
    "id" smallint NOT NULL,
    "desc" VARCHAR(16) NOT NULL
);

CREATE TABLE "dm_fact_actions" (
    "alfresco_id" smallint NOT NULL,
    "user_id" integer NOT NULL,
    "date_id" DATE NOT NULL,
    "minute_id" smallint NOT NULL,
    "action_id" smallint NOT NULL,
    "path_id" integer NOT NULL,
    "num" smallint NOT NULL,
    "src_id" bigint NOT NULL
);

CREATE TABLE "dm_reports" (
    "id" smallint NOT NULL,
    "pentaho_url" VARCHAR(1024) NOT NULL,
    "pentaho_login" VARCHAR(1024) NOT NULL,
    "pentaho_password" VARCHAR(1024) NOT NULL,
    "pentaho_path" VARCHAR(1024) NOT NULL,
    "prpt_name" VARCHAR(1024) NOT NULL,
    "name" VARCHAR(1024) NOT NULL,
    "alfresco_ftp" VARCHAR(1024) NOT NULL,
    "alfresco_port" integer NOT NULL,
    "alfresco_login" VARCHAR(1024) NOT NULL,
    "alfresco_password" VARCHAR(1024) NOT NULL,
    "alfresco_path" VARCHAR(1024) NOT NULL,
    "is_active" CHAR(1) DEFAULT 'Y' NOT NULL
);

CREATE TABLE "ope_audits" (
    "alfresco_id" smallint NOT NULL,
    "id" bigint NOT NULL,
    "application" VARCHAR(128) NOT NULL,
    "user" VARCHAR(512) NOT NULL,
    DATE DATE NOT NULL,
    "action" VARCHAR(128) NOT NULL,
    "hour" smallint NOT NULL,
    "minute" smallint NOT NULL,
    "path" VARCHAR(4096) NOT NULL,
    "node-dbid" integer,
    "type" VARCHAR(1024)
);

CREATE TABLE "stg_audits" (
    "alfresco_id" smallint NOT NULL,
    "id" bigint NOT NULL,
    "application" VARCHAR(50) NOT NULL,
    "user" VARCHAR(100),
    "time" VARCHAR(50) NOT NULL,
    "values" VARCHAR(5000)
);

CREATE TABLE "stg_rest_documents" (
    "alfresco_id" smallint NOT NULL,
    "node-dbid" integer,
    "store-protocol" VARCHAR(128),
    "store-identifier" VARCHAR(128),
    "node-uuid" VARCHAR(128),
    "name" VARCHAR(1024),
    "type" VARCHAR(1024),
    "creator" VARCHAR(1024),
    "created" VARCHAR(32),
    "locale" VARCHAR(128),
    "modifier" VARCHAR(1024),
    "modified" VARCHAR(32),
    "path" VARCHAR(3072),
    "mimetype" VARCHAR(128),
    "size" integer,
    "encoding" VARCHAR(128),
    "content-locale" VARCHAR(128),
    "parent-node-uuid" VARCHAR(128),
    "custom_aspects" VARCHAR(8192)
);

CREATE TABLE "stg_rest_documents_custom_types" (
    "alfresco_id" smallint NOT NULL,
    "node-dbid" integer,
    "custom_types" VARCHAR(8192)
);

CREATE TABLE "stg_rest_folders" (
    "alfresco_id" smallint NOT NULL,
    "node-dbid" integer,
    "store-protocol" VARCHAR(128),
    "store-identifier" VARCHAR(128),
    "node-uuid" VARCHAR(128),
    "name" VARCHAR(1024),
    "type" VARCHAR(1024),
    "creator" VARCHAR(1024),
    "created" VARCHAR(32),
    "locale" VARCHAR(128),
    "modifier" VARCHAR(1024),
    "modified" VARCHAR(32),
    "path" VARCHAR(3072),
    "parent-node-uuid" VARCHAR(128),
    "custom_aspects" VARCHAR(8192)
);

CREATE TABLE "stg_rest_folders_custom_types" (
    "alfresco_id" smallint NOT NULL,
    "node-dbid" integer,
    "custom_types" VARCHAR(8192)
);

CREATE TABLE "stg_workflow_definitions" (
    "alfresco_id" smallint NOT NULL,
    "id" VARCHAR(1024) NOT NULL,
    "name" VARCHAR(1024),
    "title" VARCHAR(1024),
    "description" VARCHAR(1024),
    "version" VARCHAR(1024),
    "url" VARCHAR(1024) NOT NULL
);

CREATE TABLE "stg_workflow_instances" (
    "alfresco_id" smallint NOT NULL,
    "id" VARCHAR(1024) NOT NULL,
    "url" VARCHAR(1024),
    "name" VARCHAR(1024),
    "title" VARCHAR(1024),
    "description" VARCHAR(1024),
    "isactive" VARCHAR(1024),
    "startdate" VARCHAR(128),
    "message" VARCHAR(1024),
    "enddate" VARCHAR(128),
    "duedate" VARCHAR(128),
    "package" VARCHAR(1024),
    "initiator" VARCHAR(256),
    "definitionurl" VARCHAR(1024)
);

CREATE TABLE "stg_workflow_items" (
    "alfresco_id" smallint NOT NULL,
    "package" VARCHAR(1024) NOT NULL,
    "ordinal" smallint NOT NULL,
    "item" VARCHAR(1024) NOT NULL
);

CREATE TABLE "stg_workflow_tasks" (
    "alfresco_id" smallint NOT NULL,
    "instance_id" VARCHAR(1024),
    "ordinal" integer,
    "id" VARCHAR(1024) NOT NULL,
    "name" VARCHAR(1024),
    "title" VARCHAR(1024),
    "description" VARCHAR(1024),
    "state" VARCHAR(128),
    "ispooled" VARCHAR(64),
    "iseditable" VARCHAR(64),
    "isreassignable" VARCHAR(64),
    "isclaimable" VARCHAR(64),
    "isreleasable" VARCHAR(64),
    "outcome" VARCHAR(64),
    "owner" VARCHAR(256),
    "bpm_startdate" VARCHAR(128),
    "bpm_duedate" VARCHAR(128),
    "bpm_completiondate" VARCHAR(128),
    "bpm_outcome" VARCHAR(1024),
    "bpm_status" VARCHAR(1024),
    "bpm_description" VARCHAR(1024)
);


CREATE VIEW "vw_dm_dim_dates" AS
 SELECT "dm_dim_dates"."id",
    "dm_dim_dates"."desc" AS "day",
    "dm_dim_dates"."day_desc",
    "dm_dim_dates"."month_id",
    "dm_dim_months"."desc" AS "month",
    "dm_dim_months"."month_desc",
    "dm_dim_months"."year_id",
    "dm_dim_years"."desc" AS "year"
   FROM "dm_dim_dates",
    "dm_dim_months",
    "dm_dim_years"
  WHERE (("dm_dim_dates"."month_id" = "dm_dim_months"."id") AND ("dm_dim_months"."year_id" = "dm_dim_years"."id"));

CREATE VIEW "vw_dm_dim_documents" AS
 SELECT "dm_dim_documents"."id",
    ((((("dm_dim_documents"."store-protocol")::"text" || '://'::"text") || ("dm_dim_documents"."store-identifier")::"text") || '/'::"text") || ("dm_dim_documents"."node-uuid")::"text") AS "noderef",
    "dm_dim_documents"."name",
    "dm_dim_documents"."path",
    "dm_dim_documents"."alfresco_id",
    "dm_dim_documents"."src_id"
   FROM "dm_dim_documents";


ALTER TABLE "vw_dm_dim_documents" OWNER TO "postgres";

--
-- TOC entry 231 (class 1259 OID 16637)
-- Name: vw_dm_dim_minutes; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW "vw_dm_dim_minutes" AS
 SELECT "dm_dim_minutes"."id",
    "dm_dim_minutes"."desc" AS "minute",
    "dm_dim_minutes"."hour_id",
    "dm_dim_hours"."desc" AS "hour"
   FROM "dm_dim_minutes",
    "dm_dim_hours"
  WHERE ("dm_dim_minutes"."hour_id" = "dm_dim_hours"."id");


ALTER TABLE "vw_dm_dim_minutes" OWNER TO "postgres";

--
-- TOC entry 232 (class 1259 OID 16641)
-- Name: vw_dm_fact_documents; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW "vw_dm_fact_documents" AS
 SELECT "dm_dim_documents"."id",
    "dm_dim_documents"."id" AS "document_id",
    "dm_dim_documents"."alfresco_id",
    "dm_dim_documents"."node_type_id",
    "dm_dim_documents"."mime_type_id",
    "dm_dim_documents"."user_creator_id",
    "dm_dim_documents"."creation_date_id",
    "dm_dim_documents"."creation_minute_id",
    "dm_dim_documents"."user_last_modifier_id",
    "dm_dim_documents"."last_modification_date_id",
    "dm_dim_documents"."last_modification_minute_id",
    "dm_dim_documents"."parent_id",
    "dm_dim_documents"."size",
    1 AS "number"
   FROM "dm_dim_documents";


ALTER TABLE "vw_dm_fact_documents" OWNER TO "postgres";

--
-- TOC entry 233 (class 1259 OID 16645)
-- Name: vw_dm_fact_repository; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW "vw_dm_fact_repository" AS
 SELECT ('DOC_'::"text" || "dm_dim_documents"."id") AS "id",
    ((((("dm_dim_documents"."store-protocol")::"text" || '://'::"text") || ("dm_dim_documents"."store-identifier")::"text") || '/'::"text") || ("dm_dim_documents"."node-uuid")::"text") AS "noderef",
    "dm_dim_documents"."name",
    "dm_dim_documents"."path",
    "dm_dim_documents"."alfresco_id",
    "dm_dim_documents"."node_type_id",
    "dm_dim_documents"."user_creator_id",
    "dm_dim_documents"."creation_date_id",
    "dm_dim_documents"."creation_minute_id",
    "dm_dim_documents"."user_last_modifier_id",
    "dm_dim_documents"."last_modification_date_id",
    "dm_dim_documents"."last_modification_minute_id",
    ('FOL_'::"text" || "dm_dim_documents"."parent_id") AS "parent_id",
    1 AS "num",
    "dm_dim_documents"."size" AS "bytes"
   FROM "dm_dim_documents"
UNION ALL
 SELECT ('FOL_'::"text" || "dm_dim_folders"."id") AS "id",
    ((((("dm_dim_folders"."store-protocol")::"text" || '://'::"text") || ("dm_dim_folders"."store-identifier")::"text") || '/'::"text") || ("dm_dim_folders"."node-uuid")::"text") AS "noderef",
    "dm_dim_folders"."name",
    "dm_dim_folders"."path",
    "dm_dim_folders"."alfresco_id",
    "dm_dim_folders"."node_type_id",
    "dm_dim_folders"."user_creator_id",
    "dm_dim_folders"."creation_date_id",
    "dm_dim_folders"."creation_minute_id",
    "dm_dim_folders"."user_last_modifier_id",
    "dm_dim_folders"."last_modification_date_id",
    "dm_dim_folders"."last_modification_minute_id",
    ('FOL_'::"text" || "dm_dim_folders"."parent_id") AS "parent_id",
    1 AS "num",
    0 AS "bytes"
   FROM "dm_dim_folders";


ALTER TABLE "vw_dm_fact_repository" OWNER TO "postgres";

--
-- TOC entry 234 (class 1259 OID 16650)
-- Name: vw_dm_min_max_date; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW "vw_dm_min_max_date" AS
 SELECT "t"."alfresco_id",
    "min"("t"."min_date") AS "min_date",
    "max"("t"."max_date") AS "max_date"
   FROM ( SELECT "dm_dim_alfresco"."id" AS "alfresco_id",
            ('now'::"text")::DATE AS "min_date",
            ('now'::"text")::DATE AS "max_date"
           FROM "dm_dim_alfresco"
        UNION ALL
         SELECT "ope_audit"."alfresco_id",
            "min"("ope_audit".DATE) AS "min_date",
            "max"("ope_audit".DATE) AS "max_date"
           FROM "ope_audits" "ope_audit"
          GROUP BY "ope_audit"."alfresco_id"
        UNION ALL
         SELECT "stg_rest_folder"."alfresco_id",
            "min"(("stg_rest_folder"."created")::DATE) AS "min_date",
            "max"(("stg_rest_folder"."created")::DATE) AS "max_date"
           FROM "stg_rest_folders" "stg_rest_folder"
          GROUP BY "stg_rest_folder"."alfresco_id"
        UNION ALL
         SELECT "stg_rest_folder"."alfresco_id",
            "min"(("stg_rest_folder"."modified")::DATE) AS "min_date",
            "max"(("stg_rest_folder"."modified")::DATE) AS "max_date"
           FROM "stg_rest_folders" "stg_rest_folder"
          GROUP BY "stg_rest_folder"."alfresco_id"
        UNION ALL
         SELECT "stg_rest_document"."alfresco_id",
            "min"(("stg_rest_document"."created")::DATE) AS "min_date",
            "max"(("stg_rest_document"."created")::DATE) AS "max_date"
           FROM "stg_rest_documents" "stg_rest_document"
          GROUP BY "stg_rest_document"."alfresco_id"
        UNION ALL
         SELECT "stg_rest_document"."alfresco_id",
            "min"(("stg_rest_document"."modified")::DATE) AS "min_date",
            "max"(("stg_rest_document"."modified")::DATE) AS "max_date"
           FROM "stg_rest_documents" "stg_rest_document"
          GROUP BY "stg_rest_document"."alfresco_id"
        UNION ALL
         SELECT "stg_workflow_instances"."alfresco_id",
            "min"(("stg_workflow_instances"."startdate")::DATE) AS "min_date",
            "max"(("stg_workflow_instances"."startdate")::DATE) AS "max_date"
           FROM "stg_workflow_instances" "stg_workflow_instances"
          GROUP BY "stg_workflow_instances"."alfresco_id"
        UNION ALL
         SELECT "stg_workflow_instances"."alfresco_id",
            "min"(("stg_workflow_instances"."enddate")::DATE) AS "min_date",
            "max"(("stg_workflow_instances"."enddate")::DATE) AS "max_date"
           FROM "stg_workflow_instances" "stg_workflow_instances"
          GROUP BY "stg_workflow_instances"."alfresco_id"
        UNION ALL
         SELECT "stg_workflow_instances"."alfresco_id",
            "min"(("stg_workflow_instances"."duedate")::DATE) AS "min_date",
            "max"(("stg_workflow_instances"."duedate")::DATE) AS "max_date"
           FROM "stg_workflow_instances" "stg_workflow_instances"
          GROUP BY "stg_workflow_instances"."alfresco_id"
        UNION ALL
         SELECT "stg_workflow_tasks"."alfresco_id",
            "min"(("stg_workflow_tasks"."bpm_startdate")::DATE) AS "min_date",
            "max"(("stg_workflow_tasks"."bpm_startdate")::DATE) AS "max_date"
           FROM "stg_workflow_tasks" "stg_workflow_tasks"
          GROUP BY "stg_workflow_tasks"."alfresco_id"
        UNION ALL
         SELECT "stg_workflow_tasks"."alfresco_id",
            "min"(("stg_workflow_tasks"."bpm_duedate")::DATE) AS "min_date",
            "max"(("stg_workflow_tasks"."bpm_duedate")::DATE) AS "max_date"
           FROM "stg_workflow_tasks" "stg_workflow_tasks"
          GROUP BY "stg_workflow_tasks"."alfresco_id"
        UNION ALL
         SELECT "stg_workflow_tasks"."alfresco_id",
            "min"(("stg_workflow_tasks"."bpm_completiondate")::DATE) AS "min_date",
            "max"(("stg_workflow_tasks"."bpm_completiondate")::DATE) AS "max_date"
           FROM "stg_workflow_tasks" "stg_workflow_tasks"
          GROUP BY "stg_workflow_tasks"."alfresco_id") "t"
  GROUP BY "t"."alfresco_id";


ALTER TABLE "vw_dm_min_max_date" OWNER TO "postgres";

--
-- TOC entry 228 (class 1259 OID 16625)
-- Name: vw_rest_documents_and_folders_path; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW "vw_rest_documents_and_folders_path" AS
 SELECT "stg_rest_documents"."alfresco_id",
    "stg_rest_documents"."node-dbid",
    "stg_rest_documents"."type",
    "stg_rest_documents"."path"
   FROM "stg_rest_documents"
UNION ALL
 SELECT "stg_rest_folders"."alfresco_id",
    "stg_rest_folders"."node-dbid",
    "stg_rest_folders"."type",
    "stg_rest_folders"."path"
   FROM "stg_rest_folders";


ALTER TABLE "vw_rest_documents_and_folders_path" OWNER TO "postgres";

--
-- TOC entry 2546 (class 0 OID 16388)
-- Dependencies: 182
-- Data for Name: dm_custom_metadata; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2593 (class 0 OID 17467)
-- Dependencies: 236
-- Data for Name: dm_data_quality; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2548 (class 0 OID 16401)
-- Dependencies: 184
-- Data for Name: dm_dim_actions; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2549 (class 0 OID 16405)
-- Dependencies: 185
-- Data for Name: dm_dim_alfresco; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO "dm_dim_alfresco" ("id", "desc", "login", "password", "url", "url_audit_suffix", "audit_limit", "url_nodes_modified_after_suffix", "url_nodes_modified_before_suffix", "node_limit", "url_workflow_definitions_suffix", "url_workflow_instances_suffix", "url_cmis_suffix", "url_get_counters", "is_active") VALUES (1, 'Default Alfresco instance', 'admin', 'admin', 'http://localhost:8080', '/alfresco/service/api/audit/query/alfresco-access?verbose=true', 50000, '/alfresco/service/AAAR/getNodesModifiedAfter', '/alfresco/service/AAAR/getNodeIdsModifiedBefore', 50000, '/alfresco/service/api/workflow-definitions', '/alfresco/service/api/workflow-instances', '/alfresco/api/-default-/cmis/versions/1.1/atom', '/alfresco/service/AAAR/getCounters', 'Y');


--
-- TOC entry 2550 (class 0 OID 16412)
-- Dependencies: 186
-- Data for Name: dm_dim_dates; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2552 (class 0 OID 16417)
-- Dependencies: 188
-- Data for Name: dm_dim_documents; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2554 (class 0 OID 16426)
-- Dependencies: 190
-- Data for Name: dm_dim_folders; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2555 (class 0 OID 16433)
-- Dependencies: 191
-- Data for Name: dm_dim_hours; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2557 (class 0 OID 16438)
-- Dependencies: 193
-- Data for Name: dm_dim_mime_types; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2558 (class 0 OID 16445)
-- Dependencies: 194
-- Data for Name: dm_dim_minutes; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2559 (class 0 OID 16448)
-- Dependencies: 195
-- Data for Name: dm_dim_months; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2561 (class 0 OID 16453)
-- Dependencies: 197
-- Data for Name: dm_dim_node_types; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2563 (class 0 OID 16462)
-- Dependencies: 199
-- Data for Name: dm_dim_paths; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2565 (class 0 OID 16471)
-- Dependencies: 201
-- Data for Name: dm_dim_users; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2567 (class 0 OID 16480)
-- Dependencies: 203
-- Data for Name: dm_dim_workflow_definitions; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2569 (class 0 OID 16489)
-- Dependencies: 205
-- Data for Name: dm_dim_workflow_instances; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2570 (class 0 OID 16496)
-- Dependencies: 206
-- Data for Name: dm_dim_workflow_items; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2572 (class 0 OID 16501)
-- Dependencies: 208
-- Data for Name: dm_dim_workflow_tasks; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2573 (class 0 OID 16508)
-- Dependencies: 209
-- Data for Name: dm_dim_years; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2574 (class 0 OID 16514)
-- Dependencies: 210
-- Data for Name: dm_fact_actions; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2592 (class 0 OID 17459)
-- Dependencies: 235
-- Data for Name: dm_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2575 (class 0 OID 16517)
-- Dependencies: 211
-- Data for Name: dm_reports; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO "dm_reports" ("id", "pentaho_url", "pentaho_login", "pentaho_password", "pentaho_path", "prpt_name", "name", "alfresco_ftp", "alfresco_port", "alfresco_login", "alfresco_password", "alfresco_path", "is_active") VALUES (5, 'http://localhost:8080/pentaho', 'admin', 'password', '/public/AAAR/Reports', 'audit_use.prpt', 'audit_use.pdf', 'localhost', 121, 'admin', 'admin', 'alfresco', 'Y');
INSERT INTO "dm_reports" ("id", "pentaho_url", "pentaho_login", "pentaho_password", "pentaho_path", "prpt_name", "name", "alfresco_ftp", "alfresco_port", "alfresco_login", "alfresco_password", "alfresco_path", "is_active") VALUES (6, 'http://localhost:8080/pentaho', 'admin', 'password', '/public/AAAR/Reports', 'document_active_users.prpt', 'document_active_users.pdf', 'localhost', 121, 'admin', 'admin', 'alfresco', 'Y');
INSERT INTO "dm_reports" ("id", "pentaho_url", "pentaho_login", "pentaho_password", "pentaho_path", "prpt_name", "name", "alfresco_ftp", "alfresco_port", "alfresco_login", "alfresco_password", "alfresco_path", "is_active") VALUES (7, 'http://localhost:8080/pentaho', 'admin', 'password', '/public/AAAR/Reports', 'document_hours_of_activity.prpt', 'document_hours_of_activity.pdf', 'localhost', 121, 'admin', 'admin', 'alfresco', 'Y');
INSERT INTO "dm_reports" ("id", "pentaho_url", "pentaho_login", "pentaho_password", "pentaho_path", "prpt_name", "name", "alfresco_ftp", "alfresco_port", "alfresco_login", "alfresco_password", "alfresco_path", "is_active") VALUES (8, 'http://localhost:8080/pentaho', 'admin', 'password', '/public/AAAR/Reports', 'document_mime_types.prpt', 'document_mime_types.pdf', 'localhost', 121, 'admin', 'admin', 'alfresco', 'Y');
INSERT INTO "dm_reports" ("id", "pentaho_url", "pentaho_login", "pentaho_password", "pentaho_path", "prpt_name", "name", "alfresco_ftp", "alfresco_port", "alfresco_login", "alfresco_password", "alfresco_path", "is_active") VALUES (9, 'http://localhost:8080/pentaho', 'admin', 'password', '/public/AAAR/Reports', 'document_size.prpt', 'document_size.pdf', 'localhost', 121, 'admin', 'admin', 'alfresco', 'Y');
INSERT INTO "dm_reports" ("id", "pentaho_url", "pentaho_login", "pentaho_password", "pentaho_path", "prpt_name", "name", "alfresco_ftp", "alfresco_port", "alfresco_login", "alfresco_password", "alfresco_path", "is_active") VALUES (10, 'http://localhost:8080/pentaho', 'admin', 'password', '/public/AAAR/Reports', 'document_types.prpt', 'document_types.pdf', 'localhost', 121, 'admin', 'admin', 'alfresco', 'Y');
INSERT INTO "dm_reports" ("id", "pentaho_url", "pentaho_login", "pentaho_password", "pentaho_path", "prpt_name", "name", "alfresco_ftp", "alfresco_port", "alfresco_login", "alfresco_password", "alfresco_path", "is_active") VALUES (11, 'http://localhost:8080/pentaho', 'admin', 'password', '/public/AAAR/Reports', 'folder_types.prpt', 'folder_types.pdf', 'localhost', 121, 'admin', 'admin', 'alfresco', 'Y');
INSERT INTO "dm_reports" ("id", "pentaho_url", "pentaho_login", "pentaho_password", "pentaho_path", "prpt_name", "name", "alfresco_ftp", "alfresco_port", "alfresco_login", "alfresco_password", "alfresco_path", "is_active") VALUES (1, 'http://localhost:8080/pentaho', 'admin', 'password', '/public/AAAR/Reports', 'audit_creation.prpt', 'audit_creation.pdf', 'localhost', 121, 'admin', 'admin', 'alfresco', 'Y');
INSERT INTO "dm_reports" ("id", "pentaho_url", "pentaho_login", "pentaho_password", "pentaho_path", "prpt_name", "name", "alfresco_ftp", "alfresco_port", "alfresco_login", "alfresco_password", "alfresco_path", "is_active") VALUES (2, 'http://localhost:8080/pentaho', 'admin', 'password', '/public/AAAR/Reports', 'audit_details.prpt', 'audit_details.pdf', 'localhost', 121, 'admin', 'admin', 'alfresco', 'Y');
INSERT INTO "dm_reports" ("id", "pentaho_url", "pentaho_login", "pentaho_password", "pentaho_path", "prpt_name", "name", "alfresco_ftp", "alfresco_port", "alfresco_login", "alfresco_password", "alfresco_path", "is_active") VALUES (3, 'http://localhost:8080/pentaho', 'admin', 'password', '/public/AAAR/Reports', 'audit_login.prpt', 'audit_login.pdf', 'localhost', 121, 'admin', 'admin', 'alfresco', 'Y');
INSERT INTO "dm_reports" ("id", "pentaho_url", "pentaho_login", "pentaho_password", "pentaho_path", "prpt_name", "name", "alfresco_ftp", "alfresco_port", "alfresco_login", "alfresco_password", "alfresco_path", "is_active") VALUES (4, 'http://localhost:8080/pentaho', 'admin', 'password', '/public/AAAR/Reports', 'audit_topTen.prpt', 'audit_topTen.pdf', 'localhost', 121, 'admin', 'admin', 'alfresco', 'Y');


--
-- TOC entry 2576 (class 0 OID 16529)
-- Dependencies: 212
-- Data for Name: log_channels; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2577 (class 0 OID 16535)
-- Dependencies: 213
-- Data for Name: log_job; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2578 (class 0 OID 16541)
-- Dependencies: 214
-- Data for Name: log_jobentry; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2579 (class 0 OID 16547)
-- Dependencies: 215
-- Data for Name: log_performance; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2580 (class 0 OID 16553)
-- Dependencies: 216
-- Data for Name: log_step; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2581 (class 0 OID 16559)
-- Dependencies: 217
-- Data for Name: log_transformations; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2582 (class 0 OID 16565)
-- Dependencies: 218
-- Data for Name: ope_audits; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2602 (class 0 OID 0)
-- Dependencies: 181
-- Name: seq_dm_custom_metadata_id; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"seq_dm_custom_metadata_id"', 1, false);


--
-- TOC entry 2603 (class 0 OID 0)
-- Dependencies: 183
-- Name: seq_dm_dim_actions_id; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"seq_dm_dim_actions_id"', 1, true);


--
-- TOC entry 2604 (class 0 OID 0)
-- Dependencies: 187
-- Name: seq_dm_dim_documents_id; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"seq_dm_dim_documents_id"', 1, true);


--
-- TOC entry 2605 (class 0 OID 0)
-- Dependencies: 189
-- Name: seq_dm_dim_folders_id; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"seq_dm_dim_folders_id"', 1, true);


--
-- TOC entry 2606 (class 0 OID 0)
-- Dependencies: 192
-- Name: seq_dm_dim_mime_types_id; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"seq_dm_dim_mime_types_id"', 1, true);


--
-- TOC entry 2607 (class 0 OID 0)
-- Dependencies: 196
-- Name: seq_dm_dim_node_types_id; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"seq_dm_dim_node_types_id"', 1, true);


--
-- TOC entry 2608 (class 0 OID 0)
-- Dependencies: 198
-- Name: seq_dm_dim_paths_id; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"seq_dm_dim_paths_id"', 1, true);


--
-- TOC entry 2609 (class 0 OID 0)
-- Dependencies: 200
-- Name: seq_dm_dim_users_id; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"seq_dm_dim_users_id"', 1, true);


--
-- TOC entry 2610 (class 0 OID 0)
-- Dependencies: 202
-- Name: seq_dm_dim_workflow_definitions_id; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"seq_dm_dim_workflow_definitions_id"', 1, true);


--
-- TOC entry 2611 (class 0 OID 0)
-- Dependencies: 204
-- Name: seq_dm_dim_workflow_instances_id; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"seq_dm_dim_workflow_instances_id"', 1, true);


--
-- TOC entry 2612 (class 0 OID 0)
-- Dependencies: 207
-- Name: seq_dm_dim_workflow_tasks_id; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"seq_dm_dim_workflow_tasks_id"', 1, true);


--
-- TOC entry 2583 (class 0 OID 16571)
-- Dependencies: 219
-- Data for Name: stg_audits; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2584 (class 0 OID 16577)
-- Dependencies: 220
-- Data for Name: stg_rest_documents; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2585 (class 0 OID 16583)
-- Dependencies: 221
-- Data for Name: stg_rest_documents_custom_types; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2586 (class 0 OID 16589)
-- Dependencies: 222
-- Data for Name: stg_rest_folders; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2587 (class 0 OID 16595)
-- Dependencies: 223
-- Data for Name: stg_rest_folders_custom_types; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2588 (class 0 OID 16601)
-- Dependencies: 224
-- Data for Name: stg_workflow_definitions; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2589 (class 0 OID 16607)
-- Dependencies: 225
-- Data for Name: stg_workflow_instances; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2590 (class 0 OID 16613)
-- Dependencies: 226
-- Data for Name: stg_workflow_items; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2591 (class 0 OID 16619)
-- Dependencies: 227
-- Data for Name: stg_workflow_tasks; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2269 (class 2606 OID 16656)
-- Name: pk_dm_custom_metadata; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_custom_metadata"
    ADD CONSTRAINT "pk_dm_custom_metadata" PRIMARY KEY ("id");


ALTER TABLE "dm_dim_actions"
    ADD CONSTRAINT "pk_dm_dim_action" PRIMARY KEY ("id");


ALTER TABLE "dm_dim_dates"
    ADD CONSTRAINT "pk_dm_dim_dates" PRIMARY KEY ("id");


ALTER TABLE "dm_dim_documents"
    ADD CONSTRAINT "pk_dm_dim_documents" PRIMARY KEY ("id");


ALTER TABLE "dm_dim_folders"
    ADD CONSTRAINT "pk_dm_dim_folders" PRIMARY KEY ("id");


ALTER TABLE "dm_dim_hours"
    ADD CONSTRAINT "pk_dm_dim_hours" PRIMARY KEY ("id");


ALTER TABLE "dm_dim_mime_types"
    ADD CONSTRAINT "pk_dm_dim_mime_types" PRIMARY KEY ("id");


ALTER TABLE "dm_dim_minutes"
    ADD CONSTRAINT "pk_dm_dim_minutes" PRIMARY KEY ("id");


ALTER TABLE "dm_dim_months"
    ADD CONSTRAINT "pk_dm_dim_months" PRIMARY KEY ("id");

ALTER TABLE "dm_dim_node_types"
    ADD CONSTRAINT "pk_dm_dim_node_types" PRIMARY KEY ("id");



ALTER TABLE "dm_dim_paths"
    ADD CONSTRAINT "pk_dm_dim_path" PRIMARY KEY ("id");


ALTER TABLE "dm_dim_users"
    ADD CONSTRAINT "pk_dm_dim_users" PRIMARY KEY ("id");


ALTER TABLE "dm_dim_workflow_definitions"
    ADD CONSTRAINT "pk_dm_dim_workflow_definitions" PRIMARY KEY ("id");

ALTER TABLE "dm_dim_workflow_instances"
    ADD CONSTRAINT "pk_dm_dim_workflow_instances" PRIMARY KEY ("id");


ALTER TABLE "dm_dim_workflow_items"
    ADD CONSTRAINT "pk_dm_dim_workflow_items" PRIMARY KEY ("alfresco_id", "workflow_instance_id", "ordinal");

ALTER TABLE "dm_dim_workflow_tasks"
    ADD CONSTRAINT "pk_dm_dim_workflow_tasks" PRIMARY KEY ("id");


ALTER TABLE "dm_dim_years"
    ADD CONSTRAINT "pk_dm_dim_years" PRIMARY KEY ("id");

ALTER TABLE "dm_reports"
    ADD CONSTRAINT "pk_reports" PRIMARY KEY ("id");


ALTER TABLE "dm_dim_alfresco"
    ADD CONSTRAINT "pk_stg_alfresco" PRIMARY KEY ("id");

ALTER TABLE "stg_audits"
    ADD CONSTRAINT "pk_stg_audit" PRIMARY KEY ("alfresco_id", "id", "application");

ALTER TABLE "ope_audits"
    ADD CONSTRAINT "pk_stg_audit_extended" PRIMARY KEY ("alfresco_id", "id", "application");

ALTER TABLE "stg_workflow_instances"
    ADD CONSTRAINT "pk_stg_workflow_instances" PRIMARY KEY ("alfresco_id", "id");

ALTER TABLE "stg_workflow_items"
    ADD CONSTRAINT "pk_stg_workflow_packages" PRIMARY KEY ("alfresco_id", "package", "item");

ALTER TABLE "stg_workflow_tasks"
    ADD CONSTRAINT "pk_stg_workflow_tasks" PRIMARY KEY ("alfresco_id", "id");

ALTER TABLE "stg_rest_documents"
    ADD CONSTRAINT "uni_document_id" UNIQUE ("alfresco_id", "node-dbid");

ALTER TABLE "stg_rest_folders"
    ADD CONSTRAINT "uni_folder_id" UNIQUE ("alfresco_id", "node-dbid");

ALTER TABLE "dm_custom_metadata"
    ADD CONSTRAINT "unq_dm_custom_metadata" UNIQUE ("class", "name");

ALTER TABLE "dm_dim_documents"
    ADD CONSTRAINT "unq_dm_dim_documents" UNIQUE ("alfresco_id", "src_id");

ALTER TABLE "dm_dim_folders"
    ADD CONSTRAINT "unq_dm_dim_folders" UNIQUE ("alfresco_id", "src_id");






ALTER TABLE "dm_custom_metadata"
    ADD CONSTRAINT "fk_dm_custom_metadata_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2423 (class 2606 OID 17471)
-- Name: fk_dm_data_quality_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_data_quality"
    ADD CONSTRAINT "fk_dm_data_quality_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2353 (class 2606 OID 16773)
-- Name: fk_dm_dim_action_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_actions"
    ADD CONSTRAINT "fk_dm_dim_action_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2354 (class 2606 OID 16778)
-- Name: fk_dm_dim_dates_dm_dim_months; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_dates"
    ADD CONSTRAINT "fk_dm_dim_dates_dm_dim_months" FOREIGN KEY ("month_id") REFERENCES "dm_dim_months"("id");


--
-- TOC entry 2355 (class 2606 OID 16783)
-- Name: fk_dm_dim_documents_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_documents"
    ADD CONSTRAINT "fk_dm_dim_documents_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2356 (class 2606 OID 16788)
-- Name: fk_dm_dim_documents_dm_dim_dates_creation; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_documents"
    ADD CONSTRAINT "fk_dm_dim_documents_dm_dim_dates_creation" FOREIGN KEY ("creation_date_id") REFERENCES "dm_dim_dates"("id");


--
-- TOC entry 2357 (class 2606 OID 16793)
-- Name: fk_dm_dim_documents_dm_dim_dates_last_modification; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_documents"
    ADD CONSTRAINT "fk_dm_dim_documents_dm_dim_dates_last_modification" FOREIGN KEY ("last_modification_date_id") REFERENCES "dm_dim_dates"("id");


--
-- TOC entry 2358 (class 2606 OID 16798)
-- Name: fk_dm_dim_documents_dm_dim_folders_parent; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_documents"
    ADD CONSTRAINT "fk_dm_dim_documents_dm_dim_folders_parent" FOREIGN KEY ("parent_id") REFERENCES "dm_dim_folders"("id");


--
-- TOC entry 2359 (class 2606 OID 16803)
-- Name: fk_dm_dim_documents_dm_dim_mime_types; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_documents"
    ADD CONSTRAINT "fk_dm_dim_documents_dm_dim_mime_types" FOREIGN KEY ("mime_type_id") REFERENCES "dm_dim_mime_types"("id");


--
-- TOC entry 2360 (class 2606 OID 16808)
-- Name: fk_dm_dim_documents_dm_dim_minutes_creation; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_documents"
    ADD CONSTRAINT "fk_dm_dim_documents_dm_dim_minutes_creation" FOREIGN KEY ("creation_minute_id") REFERENCES "dm_dim_minutes"("id");


--
-- TOC entry 2361 (class 2606 OID 16813)
-- Name: fk_dm_dim_documents_dm_dim_minutes_last_modification; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_documents"
    ADD CONSTRAINT "fk_dm_dim_documents_dm_dim_minutes_last_modification" FOREIGN KEY ("last_modification_minute_id") REFERENCES "dm_dim_minutes"("id");


--
-- TOC entry 2362 (class 2606 OID 16818)
-- Name: fk_dm_dim_documents_dm_dim_node_types; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_documents"
    ADD CONSTRAINT "fk_dm_dim_documents_dm_dim_node_types" FOREIGN KEY ("node_type_id") REFERENCES "dm_dim_node_types"("id");


--
-- TOC entry 2363 (class 2606 OID 16823)
-- Name: fk_dm_dim_documents_dm_dim_users_creator; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_documents"
    ADD CONSTRAINT "fk_dm_dim_documents_dm_dim_users_creator" FOREIGN KEY ("user_creator_id") REFERENCES "dm_dim_users"("id");


--
-- TOC entry 2364 (class 2606 OID 16828)
-- Name: fk_dm_dim_documents_dm_dim_users_last_modifier; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_documents"
    ADD CONSTRAINT "fk_dm_dim_documents_dm_dim_users_last_modifier" FOREIGN KEY ("user_last_modifier_id") REFERENCES "dm_dim_users"("id");


--
-- TOC entry 2365 (class 2606 OID 16833)
-- Name: fk_dm_dim_folders_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_folders"
    ADD CONSTRAINT "fk_dm_dim_folders_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2366 (class 2606 OID 16838)
-- Name: fk_dm_dim_folders_dm_dim_dates_creation; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_folders"
    ADD CONSTRAINT "fk_dm_dim_folders_dm_dim_dates_creation" FOREIGN KEY ("creation_date_id") REFERENCES "dm_dim_dates"("id");


--
-- TOC entry 2367 (class 2606 OID 16843)
-- Name: fk_dm_dim_folders_dm_dim_dates_last_modification; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_folders"
    ADD CONSTRAINT "fk_dm_dim_folders_dm_dim_dates_last_modification" FOREIGN KEY ("last_modification_date_id") REFERENCES "dm_dim_dates"("id");


--
-- TOC entry 2368 (class 2606 OID 16848)
-- Name: fk_dm_dim_folders_dm_dim_folders_aprent; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_folders"
    ADD CONSTRAINT "fk_dm_dim_folders_dm_dim_folders_aprent" FOREIGN KEY ("parent_id") REFERENCES "dm_dim_folders"("id");


--
-- TOC entry 2369 (class 2606 OID 16853)
-- Name: fk_dm_dim_folders_dm_dim_minutes_creation; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_folders"
    ADD CONSTRAINT "fk_dm_dim_folders_dm_dim_minutes_creation" FOREIGN KEY ("creation_minute_id") REFERENCES "dm_dim_minutes"("id");


--
-- TOC entry 2370 (class 2606 OID 16858)
-- Name: fk_dm_dim_folders_dm_dim_minutes_last_modification; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_folders"
    ADD CONSTRAINT "fk_dm_dim_folders_dm_dim_minutes_last_modification" FOREIGN KEY ("last_modification_minute_id") REFERENCES "dm_dim_minutes"("id");


--
-- TOC entry 2371 (class 2606 OID 16863)
-- Name: fk_dm_dim_folders_dm_dim_node_types; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_folders"
    ADD CONSTRAINT "fk_dm_dim_folders_dm_dim_node_types" FOREIGN KEY ("node_type_id") REFERENCES "dm_dim_node_types"("id");


--
-- TOC entry 2372 (class 2606 OID 16868)
-- Name: fk_dm_dim_folders_dm_dim_users_creator; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_folders"
    ADD CONSTRAINT "fk_dm_dim_folders_dm_dim_users_creator" FOREIGN KEY ("user_creator_id") REFERENCES "dm_dim_users"("id");


--
-- TOC entry 2373 (class 2606 OID 16873)
-- Name: fk_dm_dim_folders_dm_dim_users_last_modifier; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_folders"
    ADD CONSTRAINT "fk_dm_dim_folders_dm_dim_users_last_modifier" FOREIGN KEY ("user_last_modifier_id") REFERENCES "dm_dim_users"("id");


--
-- TOC entry 2374 (class 2606 OID 16878)
-- Name: fk_dm_dim_mime_types_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_mime_types"
    ADD CONSTRAINT "fk_dm_dim_mime_types_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2375 (class 2606 OID 16883)
-- Name: fk_dm_dim_minutes_dm_dim_hours; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_minutes"
    ADD CONSTRAINT "fk_dm_dim_minutes_dm_dim_hours" FOREIGN KEY ("hour_id") REFERENCES "dm_dim_hours"("id");


--
-- TOC entry 2376 (class 2606 OID 16888)
-- Name: fk_dm_dim_months_dm_dim_years; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_months"
    ADD CONSTRAINT "fk_dm_dim_months_dm_dim_years" FOREIGN KEY ("year_id") REFERENCES "dm_dim_years"("id");


--
-- TOC entry 2377 (class 2606 OID 16893)
-- Name: fk_dm_dim_node_types_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_node_types"
    ADD CONSTRAINT "fk_dm_dim_node_types_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2378 (class 2606 OID 16898)
-- Name: fk_dm_dim_path_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_paths"
    ADD CONSTRAINT "fk_dm_dim_path_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2379 (class 2606 OID 17476)
-- Name: fk_dm_dim_paths_dm_dim_documents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_paths"
    ADD CONSTRAINT "fk_dm_dim_paths_dm_dim_documents" FOREIGN KEY ("document_id") REFERENCES "dm_dim_documents"("id") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 2380 (class 2606 OID 17481)
-- Name: fk_dm_dim_paths_dm_dim_folders; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_paths"
    ADD CONSTRAINT "fk_dm_dim_paths_dm_dim_folders" FOREIGN KEY ("folder_id") REFERENCES "dm_dim_folders"("id") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 2381 (class 2606 OID 16913)
-- Name: fk_dm_dim_users_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_users"
    ADD CONSTRAINT "fk_dm_dim_users_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2382 (class 2606 OID 16918)
-- Name: fk_dm_dim_workflow_definitions_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_definitions"
    ADD CONSTRAINT "fk_dm_dim_workflow_definitions_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2383 (class 2606 OID 16923)
-- Name: fk_dm_dim_workflow_instances_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_instances"
    ADD CONSTRAINT "fk_dm_dim_workflow_instances_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2384 (class 2606 OID 16928)
-- Name: fk_dm_dim_workflow_instances_dm_dim_dates_due; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_instances"
    ADD CONSTRAINT "fk_dm_dim_workflow_instances_dm_dim_dates_due" FOREIGN KEY ("due_date_id") REFERENCES "dm_dim_dates"("id");


--
-- TOC entry 2385 (class 2606 OID 16933)
-- Name: fk_dm_dim_workflow_instances_dm_dim_dates_end; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_instances"
    ADD CONSTRAINT "fk_dm_dim_workflow_instances_dm_dim_dates_end" FOREIGN KEY ("end_date_id") REFERENCES "dm_dim_dates"("id");


--
-- TOC entry 2386 (class 2606 OID 16938)
-- Name: fk_dm_dim_workflow_instances_dm_dim_dates_start; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_instances"
    ADD CONSTRAINT "fk_dm_dim_workflow_instances_dm_dim_dates_start" FOREIGN KEY ("start_date_id") REFERENCES "dm_dim_dates"("id");


--
-- TOC entry 2387 (class 2606 OID 16943)
-- Name: fk_dm_dim_workflow_instances_dm_dim_minutes_due; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_instances"
    ADD CONSTRAINT "fk_dm_dim_workflow_instances_dm_dim_minutes_due" FOREIGN KEY ("due_minute_id") REFERENCES "dm_dim_minutes"("id");


--
-- TOC entry 2388 (class 2606 OID 16948)
-- Name: fk_dm_dim_workflow_instances_dm_dim_minutes_end; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_instances"
    ADD CONSTRAINT "fk_dm_dim_workflow_instances_dm_dim_minutes_end" FOREIGN KEY ("end_minute_id") REFERENCES "dm_dim_minutes"("id");


--
-- TOC entry 2389 (class 2606 OID 16953)
-- Name: fk_dm_dim_workflow_instances_dm_dim_minutes_start; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_instances"
    ADD CONSTRAINT "fk_dm_dim_workflow_instances_dm_dim_minutes_start" FOREIGN KEY ("start_minute_id") REFERENCES "dm_dim_minutes"("id");


--
-- TOC entry 2390 (class 2606 OID 16958)
-- Name: fk_dm_dim_workflow_instances_dm_dim_users; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_instances"
    ADD CONSTRAINT "fk_dm_dim_workflow_instances_dm_dim_users" FOREIGN KEY ("initiator_id") REFERENCES "dm_dim_users"("id");


--
-- TOC entry 2391 (class 2606 OID 16963)
-- Name: fk_dm_dim_workflow_instances_dm_dim_workflow_definitions; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_instances"
    ADD CONSTRAINT "fk_dm_dim_workflow_instances_dm_dim_workflow_definitions" FOREIGN KEY ("definition_id") REFERENCES "dm_dim_workflow_definitions"("id");


--
-- TOC entry 2392 (class 2606 OID 16968)
-- Name: fk_dm_dim_workflow_items_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_items"
    ADD CONSTRAINT "fk_dm_dim_workflow_items_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2393 (class 2606 OID 16973)
-- Name: fk_dm_dim_workflow_items_dm_dim_documents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_items"
    ADD CONSTRAINT "fk_dm_dim_workflow_items_dm_dim_documents" FOREIGN KEY ("document_id") REFERENCES "dm_dim_documents"("id");


--
-- TOC entry 2394 (class 2606 OID 16978)
-- Name: fk_dm_dim_workflow_items_dm_dim_workflow_instances; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_items"
    ADD CONSTRAINT "fk_dm_dim_workflow_items_dm_dim_workflow_instances" FOREIGN KEY ("workflow_instance_id") REFERENCES "dm_dim_workflow_instances"("id");


--
-- TOC entry 2395 (class 2606 OID 16983)
-- Name: fk_dm_dim_workflow_tasks_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_tasks"
    ADD CONSTRAINT "fk_dm_dim_workflow_tasks_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2396 (class 2606 OID 16988)
-- Name: fk_dm_dim_workflow_tasks_dm_dim_dates_completion; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_tasks"
    ADD CONSTRAINT "fk_dm_dim_workflow_tasks_dm_dim_dates_completion" FOREIGN KEY ("completion_date_id") REFERENCES "dm_dim_dates"("id");


--
-- TOC entry 2397 (class 2606 OID 16993)
-- Name: fk_dm_dim_workflow_tasks_dm_dim_dates_due; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_tasks"
    ADD CONSTRAINT "fk_dm_dim_workflow_tasks_dm_dim_dates_due" FOREIGN KEY ("due_date_id") REFERENCES "dm_dim_dates"("id");


--
-- TOC entry 2398 (class 2606 OID 16998)
-- Name: fk_dm_dim_workflow_tasks_dm_dim_dates_start; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_tasks"
    ADD CONSTRAINT "fk_dm_dim_workflow_tasks_dm_dim_dates_start" FOREIGN KEY ("start_date_id") REFERENCES "dm_dim_dates"("id");


--
-- TOC entry 2399 (class 2606 OID 17003)
-- Name: fk_dm_dim_workflow_tasks_dm_dim_minutes_completion; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_tasks"
    ADD CONSTRAINT "fk_dm_dim_workflow_tasks_dm_dim_minutes_completion" FOREIGN KEY ("completion_minute_id") REFERENCES "dm_dim_minutes"("id");


--
-- TOC entry 2400 (class 2606 OID 17008)
-- Name: fk_dm_dim_workflow_tasks_dm_dim_minutes_due; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_tasks"
    ADD CONSTRAINT "fk_dm_dim_workflow_tasks_dm_dim_minutes_due" FOREIGN KEY ("due_minute_id") REFERENCES "dm_dim_minutes"("id");


--
-- TOC entry 2401 (class 2606 OID 17013)
-- Name: fk_dm_dim_workflow_tasks_dm_dim_minutes_start; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_tasks"
    ADD CONSTRAINT "fk_dm_dim_workflow_tasks_dm_dim_minutes_start" FOREIGN KEY ("start_minute_id") REFERENCES "dm_dim_minutes"("id");


--
-- TOC entry 2402 (class 2606 OID 17018)
-- Name: fk_dm_dim_workflow_tasks_dm_dim_users; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_tasks"
    ADD CONSTRAINT "fk_dm_dim_workflow_tasks_dm_dim_users" FOREIGN KEY ("owner_id") REFERENCES "dm_dim_users"("id");


--
-- TOC entry 2403 (class 2606 OID 17023)
-- Name: fk_dm_dim_workflow_tasks_dm_dim_workflow_instances; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_dim_workflow_tasks"
    ADD CONSTRAINT "fk_dm_dim_workflow_tasks_dm_dim_workflow_instances" FOREIGN KEY ("instance_id") REFERENCES "dm_dim_workflow_instances"("id");


--
-- TOC entry 2404 (class 2606 OID 17028)
-- Name: fk_dm_fact_actions_dm_dim_actions; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_fact_actions"
    ADD CONSTRAINT "fk_dm_fact_actions_dm_dim_actions" FOREIGN KEY ("action_id") REFERENCES "dm_dim_actions"("id");


--
-- TOC entry 2405 (class 2606 OID 17033)
-- Name: fk_dm_fact_actions_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_fact_actions"
    ADD CONSTRAINT "fk_dm_fact_actions_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2406 (class 2606 OID 17038)
-- Name: fk_dm_fact_actions_dm_dim_dates; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_fact_actions"
    ADD CONSTRAINT "fk_dm_fact_actions_dm_dim_dates" FOREIGN KEY ("date_id") REFERENCES "dm_dim_dates"("id");


--
-- TOC entry 2407 (class 2606 OID 17043)
-- Name: fk_dm_fact_actions_dm_dim_minutes; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_fact_actions"
    ADD CONSTRAINT "fk_dm_fact_actions_dm_dim_minutes" FOREIGN KEY ("minute_id") REFERENCES "dm_dim_minutes"("id");


--
-- TOC entry 2408 (class 2606 OID 17048)
-- Name: fk_dm_fact_actions_dm_dim_paths; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_fact_actions"
    ADD CONSTRAINT "fk_dm_fact_actions_dm_dim_paths" FOREIGN KEY ("path_id") REFERENCES "dm_dim_paths"("id");


--
-- TOC entry 2409 (class 2606 OID 17053)
-- Name: fk_dm_fact_actions_dm_dim_users; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_fact_actions"
    ADD CONSTRAINT "fk_dm_fact_actions_dm_dim_users" FOREIGN KEY ("user_id") REFERENCES "dm_dim_users"("id");


--
-- TOC entry 2422 (class 2606 OID 17462)
-- Name: fk_dm_logs_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "dm_logs"
    ADD CONSTRAINT "fk_dm_logs_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2411 (class 2606 OID 17058)
-- Name: fk_stg_audit_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "stg_audits"
    ADD CONSTRAINT "fk_stg_audit_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2410 (class 2606 OID 17063)
-- Name: fk_stg_audit_extended_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "ope_audits"
    ADD CONSTRAINT "fk_stg_audit_extended_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2413 (class 2606 OID 16712)
-- Name: fk_stg_rest_documents_custom_types_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "stg_rest_documents_custom_types"
    ADD CONSTRAINT "fk_stg_rest_documents_custom_types_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2414 (class 2606 OID 16717)
-- Name: fk_stg_rest_documents_custom_types_stg_rest_documents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "stg_rest_documents_custom_types"
    ADD CONSTRAINT "fk_stg_rest_documents_custom_types_stg_rest_documents" FOREIGN KEY ("alfresco_id", "node-dbid") REFERENCES "stg_rest_documents"("alfresco_id", "node-dbid");


--
-- TOC entry 2412 (class 2606 OID 16707)
-- Name: fk_stg_rest_documents_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "stg_rest_documents"
    ADD CONSTRAINT "fk_stg_rest_documents_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2416 (class 2606 OID 16729)
-- Name: fk_stg_rest_folders_custom_types_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "stg_rest_folders_custom_types"
    ADD CONSTRAINT "fk_stg_rest_folders_custom_types_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2417 (class 2606 OID 16734)
-- Name: fk_stg_rest_folders_custom_types_stg_rest_folders; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "stg_rest_folders_custom_types"
    ADD CONSTRAINT "fk_stg_rest_folders_custom_types_stg_rest_folders" FOREIGN KEY ("alfresco_id", "node-dbid") REFERENCES "stg_rest_folders"("alfresco_id", "node-dbid");


--
-- TOC entry 2415 (class 2606 OID 16724)
-- Name: fk_stg_rest_folders_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "stg_rest_folders"
    ADD CONSTRAINT "fk_stg_rest_folders_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2418 (class 2606 OID 17068)
-- Name: fk_stg_workflow_definitions_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "stg_workflow_definitions"
    ADD CONSTRAINT "fk_stg_workflow_definitions_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2419 (class 2606 OID 17073)
-- Name: fk_stg_workflow_instances_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "stg_workflow_instances"
    ADD CONSTRAINT "fk_stg_workflow_instances_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2420 (class 2606 OID 17078)
-- Name: fk_stg_workflow_packages_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "stg_workflow_items"
    ADD CONSTRAINT "fk_stg_workflow_packages_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2421 (class 2606 OID 17083)
-- Name: fk_stg_workflow_tasks_dm_dim_alfresco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "stg_workflow_tasks"
    ADD CONSTRAINT "fk_stg_workflow_tasks_dm_dim_alfresco" FOREIGN KEY ("alfresco_id") REFERENCES "dm_dim_alfresco"("id");


--
-- TOC entry 2600 (class 0 OID 0)
-- Dependencies: 7
-- Name: public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE ALL ON SCHEMA "public" FROM PUBLIC;
REVOKE ALL ON SCHEMA "public" FROM "postgres";
GRANT ALL ON SCHEMA "public" TO "postgres";
GRANT ALL ON SCHEMA "public" TO PUBLIC;


-- Completed on 2016-05-07 22:57:18 CEST

--
-- PostgreSQL database dump complete
--

